---
configure_git: false 
git_email: "tomwmoore@hotmail.com"
git_username: "Tom Moore"
git_editor: "nvim"

install_dotfiles: true
install_tmux: true
install_python: true
install_vscode: true
install_picocom: true
install_neovim: true
install_rust: true
install_rust_packages: true
install_docker: true
install_vlc: false
install_libreoffice: false
install_sqlite3: false
install_dracula_theme: true
install_spotify: true
install_kicad: false

install_nrf_vscode_extensions: false
